[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
monopoly_program = "H37P3e9ZRpNHSLacyKCNVcn6PRxjoX5jaTV4pUEXYYWv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "key.json"

[scripts]
test = ""
